# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yWhQzz6na5ueOs2ofijzs7__uM6Ia2LF

Dado un número entero, determinar si ese número corresponde al código ASCII de una vocal minúscula.
"""

x : int
x = int(input("ingrese un valor digito: "))
if x == 97:
  print("el numero 97 corresponde a la vocal minuscula a ")
elif x == 101:
  print("el numero 101 corresponde a la vocal minuscula e")
elif x == 105:
  print("el numero 105 corresponde a la vocal minuscula i")
elif x == 111:
  print("el numero 111 corresponde a la vocal minuscula o")
elif x == 117:
  print("el numero 117 corresponde a la vocal minuscula u")
else:
 print("no pertenece a ninguna vocal")

"""Dada una cadena de longitud 1, determine si el código ASCII de primera letra de la cadena es par o no."""

cadena_longitud = input("ingrese una cadena de longitud 1 ")
numero = ord(cadena_longitud)
if numero % 2 == 0:
  print("es par")
else:
  print("no es par")

"""Dado un carácter, construya un programa en Python para determinar si el carácter es un dígito o no."""

caracter = input("ingrese un caracter: ")
if caracter >= "0" and caracter <= "9":
    print("el caracter es digito")
else:
  print("no es digito")

"""Realice un programa que lea dos números reales y determine si el primero es múltiplo del segundo."""

x : float
n : float
x = float(input("ingrese un numero: "))
n = float(input("ingrese otro numero: "))
if n % x == 0:
  print("es multiplo de " + str(n))
else:
  print("no es multiplo de " + str(x))

"""Dado un número real x, construya un programa que permita determinar si el número es positivo, negativo o cero. Para cada caso de debe imprimir el texto que se especifica a continuación:"""

x : float
x = float(input("ingrese un numero: "))
if x < 0:
  print("El número " + str(x) + " es negativo")
elif x == 0:
  print("El número " + str(x) + " es el neutro para la suma")
else:
  print("El numero " + str(x) + " es positivo")

"""Dado el centro y el radio de un círculo, determinar si un punto de R2 pertenece o no al interior del círculo."""

x : float
y : float
cen_h : float
cen_k : float
r : float
r = float(input("ingrese un calor para el radio: "))
x = float(input("ingrese un valor para x "))
y = float(input("ingrese un valor para y "))
cen_h = float(input("ingrese un valor para el centro en x "))
cen_k = float(input("ingrese un valor para el centro en y "))
if (x-cen_h)**2 + (y-cen_k)**2 <= r*2:
  print("el punto si pertenece al interior")
else:
  print("el punto no pertenece al interior")

"""Dadas tres longitudes positivas, determinar si con esas longitudes se puede construir un triángulo."""

cateto_o : float
cateto_a : float
cateto_h : float

cateto_o = float(input("digite un valor para el cateto numero 1: "))
cateto_a = float(input("digite un valor para el cateto numero 2: "))
cateto_h = float(input("digite un valor para el cateto numero 3: "))

if cateto_o + cateto_h > cateto_a and cateto_a + cateto_h > cateto_o and cateto_o + cateto_a > cateto_h:
  print("si se puede construir un triangulo con las medidas dadas")
else:
  print("no se puede construir un triangulo, porfavor cambie las medidas... ")

"""Escriba un programa que reciba el nombre en minúsculas de un país de America y retorne la ciudad capital, si el país no pertenece al continente debe arrojar país no identificado (Utilice match-case)."""

pais = input("ingrese un pais de america: ")

match pais:
  case "colombia":
    print("la capital de colombia es bogota")
  case "argentina":
    print("la capital de argentina es buenos aires")
  case "brasil":
    print("la capital de brasil es brasilia")
  case "puerto rico":
    print("la capital de puertorico es san juan")
  case "guatemala":
    print("la capital de guatemala es ciudad de guatemala")
  case "honduras":
    print("la capital de honduras es tegucigalpa")
  case "mexico":
    print("la capital de mexico es ciudad de mexico")
  case "chile":
    print("la capital de chile es santiago de chile")
  case "venezuela":
    print("la capital de venezuela es caracas")
  case "el salvador":
    print("la capital de el salvador es san savador")
  case "nicaragua":
    print("la capital de nicaragua es managua")
  case "costa rica":
    print("la capital de costa rica es san jose")
  case "panama":
    print("la capital de panama es panama")
  case "bolivia":
    print("la capital de bolivia es sucre")
  case "ecuador":
    print("la capital de ecuador es quito")
  case "paraguay":
    print("la capital de paraguay es asuncion")
  case "uruguay":
    print("la capital de uruguay es montevideo")
  case "peru":
    print("la capital de peru es lima")
  case "canada":
    print("la capital de canada es ottawa")
  case "estados unidos":
   print("la capital de estados unidos es washington D.C")
  case _:
   print("ese pais no pertenece a america")